name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test secrets
      run: echo ${{ secrets.AWS_ACCESS_KEY_ID }} && echo ${{ secrets.AWS_SECRET_ACCESS_KEY }} && echo ${{ secrets.AWS_REGION }}
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: login to aws
      run: aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 026858712465.dkr.ecr.eu-central-1.amazonaws.com
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag resume-builder:$(date +%s)
    - name: docker tagging
      run: docker tag resume-builder:$(date +%s) 026858712465.dkr.ecr.eu-central-1.amazonaws.com/resume-builder:$(date +%s)
    - name: docker push
      run: docker push 026858712465.dkr.ecr.eu-central-1.amazonaws.com/resume-builder:$(date +%s)
